#!/bin/bash
echo "🔍 Claude Code 설정 확인"
echo ""
echo "📂 Working Directory: $(pwd)"
echo "🏠 CLAUDE_HOME: ${CLAUDE_HOME:-'❌ 설정 안됨'}"
echo "💼 CLAUDE_WORK_DIR: ${CLAUDE_WORK_DIR:-'❌ 설정 안됨'}"
echo ""
echo "📁 디렉토리 구조:"
ls -la ~/.claude/ 2>/dev/null | head -10 || echo "❌ .claude 디렉토리 없음"
echo ""
echo "🔧 MCP 서버:"
ls -1 ~/.claude/mcp-servers/ 2>/dev/null || echo "❌ MCP 서버 없음"
echo ""
echo "🎯 Skills:"
ls -1 ~/.claude/skills/ 2>/dev/null | head -10 || echo "❌ Skills 없음"
echo ""
echo "✅ 확인 완료"
